name: Docker publish

on:
  pull_request:
    branches: [ master, development ]

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

env:
  IMAGE_NAME: robin-copy-api

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      FINNHUB_TOKEN: 'c35449iad3idcjopf9vg'
      MOCKED_EXTERNAL_API: 'false'
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Gradle
        run: ./gradlew build
